// Self-contained layout and native-selection regression.
const fs = require('node:fs');
const { runFixture } = require('./browser-helpers.cjs');
const ts = require('typescript');
const source = ['compare-selectors', 'compare-bubbles', 'compare-perks'].map(name => fs.readFileSync('src/'+name+'.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')).join('\n');
const script = ts.transpileModule(`const t=key=>key, getLocalizedPerkName=(_hash,name)=>name, getPerkIcon=()=>undefined, getPerkHashFromEnglish=()=>null;\n` + source + `
const results=[];
function check(value,label){if(!value)throw new Error(label);results.push(label);}
const frame=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
async function run(){
 for(const flavor of ['release','beta','legacy']){
  const fixture=document.getElementById('fixture');
  const bucketClass=flavor==='release'?'opaque_grid':flavor==='beta'?'Compare_bucket_test':'Compare-bucket-test';
  const headerClass=flavor==='release'?'opaque_header':flavor==='beta'?'CompareItem_headerContainer_test':'CompareItem-headerContainer-test';
  const categories={}, perksMap={}, all=[];
  const icon=hash=>'https://www.bungie.net/common/'+hash+'.png';
  const nativeSocket=(slot,i)=>{
   const base=i*10; categories[slotKeys[i]]=[1,2,3].map(n=>'Perk '+(base+n));
   [1,2,3].forEach(n=>perksMap[base+n]={name:'Perk '+(base+n),icon:icon(base+n)});
   [4,2,1].forEach((n,index)=>all.push({type:slot,name:'Perk '+(base+n),hash:base+n,icon:icon(base+n),rankIndex:index+1}));
   return '<div class="native-socket">'+[1,2,3].map(n=>'<div role="button" class="native-plug" title="DIM tooltip"><div><svg viewBox="0 0 100 100" class="native-circle"><circle cx="50" cy="50" r="48"/><image href="'+icon(base+n)+'" width="80" height="80"/><circle cx="50" cy="50" r="46" fill="transparent"/></svg></div></div>').join('')+'</div>';
  };
  const socketHTML=slots.map(nativeSocket).join('');
  fixture.innerHTML='<div role="dialog"><div class="'+bucketClass+'" style="grid-template-rows:80px auto;grid-template-columns:80px;display:grid;grid-auto-flow:column;grid-auto-columns:220px 1px"><div></div><div role="rowheader">Perks</div>'+[1,2].map(id=>'<div class="'+headerClass+'"><div><div class="item" data-aegis-item-hash="'+id+'"></div></div></div><div role="cell"><div style="display:flex;gap:4px">'+socketHTML+'</div></div><div></div><div></div>').join('')+'</div></div>';
  fixture.querySelectorAll('.item').forEach(item=>item.dataset.aegisWeaponPossiblePerks=JSON.stringify(categories));
  const bucket=fixture.querySelector(COMPARE_BUCKET_SELECTOR);
  check(!!bucket,flavor+' grid detected');
  const native=[...fixture.querySelectorAll('[role="button"]')];
  let clicks=0; native.forEach(node=>node.addEventListener('click',()=>clicks++));
  const data={sheetWeapon:{},sheetWeaponPvE:{},sheetWeaponPvP:{},perksMap,activeHashes:[1,11,21,31,41],sheetPerks:{all},sheetPerksPvE:{all},sheetPerksPvP:{all:all.filter(p=>p.rankIndex===1)}};
  let enabled=true,order='sheet',mode='pve';
  let secondData;
  const controller=initComparePerks({getData:item=>item.dataset.aegisItemHash==='2'&&secondData||data,getMode:()=>mode,getOrder:()=>order,enabled:()=>enabled});
  controller.refresh();await frame();
  check(fixture.querySelectorAll('[data-aegis-compare-slot]').length===10,flavor+' all five slots in both columns');
  check(!fixture.querySelector('.aegis-compare-grade,.aegis-compare-table'),flavor+' no duplicate grades or text table');
  check(native.every((node,i)=>node===fixture.querySelectorAll('[role="button"]')[i]),flavor+' native nodes and DOM order preserved');
  native[1].click(); check(clicks===1,flavor+' native click handler preserved');
  const socket=fixture.querySelector('[data-aegis-compare-slot]');
  const visual=()=>[...socket.querySelectorAll('[data-aegis-compare-state]')].sort((a,b)=>Number(getComputedStyle(a).order)-Number(getComputedStyle(b).order));
  check(visual().map(n=>n.dataset.aegisCompareState).join(',')==='missing,selectable,active,other',flavor+' Aegis order and all four colors');
  const positions=visual().map(n=>n.getBoundingClientRect());
  const gaps=positions.slice(1).map((r,i)=>r.top-positions[i].bottom);
  check(gaps.every(gap=>Math.abs(gap-gaps[0])<0.1),flavor+' uniform grid spacing including gray perks');
  check(['none','normal'].includes(getComputedStyle(socket,'::before').content),flavor+' column headers removed');
  fixture.querySelector('[data-aegis-perk-layout-choice="list"]').click();await frame();
  const label=socket.querySelector(':scope > .aegis-perk-label');
  check(label.textContent==='Perk 1',flavor+' separate selected name restored');
  check(!socket.querySelector('[data-aegis-compare-state] .aegis-perk-label'),flavor+' bubbles contain no inline names');
  check(visual().every(node=>node.getBoundingClientRect().width===28),flavor+' all list bubbles remain circular');
  check(Math.abs(visual()[0].getBoundingClientRect().left-Math.max(...[...socket.parentElement.querySelectorAll(".aegis-perk-label")].map(node=>node.getBoundingClientRect().right))-4)<.1,flavor+' name-to-bubble gap is four pixels');
  const savedName=data.perksMap[2].name;
  data.perksMap[2].name='A much longer unselected perk name';controller.refresh();await frame();
  const before=socket.parentElement.getBoundingClientRect().width;
  const stablePositions=()=>JSON.stringify(visual().map(node=>[node.getBoundingClientRect().x,node.getBoundingClientRect().y]));
  const beforePositions=stablePositions();
  data.activeHashes=[2,12,22,32,42];controller.refresh();await frame();
  check(label.textContent===data.perksMap[2].name,flavor+' separate name follows long selection');
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' longest selection preserves column width and bubble positions');
  data.activeHashes=[1,11,21,31,41];controller.refresh();await frame();
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' shorter selection retains reserved width');
  data.activeHashes=[];controller.refresh();await frame();
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' empty selection retains reserved width');
  data.perksMap[2].name=savedName;
  data.activeHashes=[1,11,21,31,41];controller.refresh();await frame();
  fixture.querySelector('[data-aegis-perk-layout-choice="grid"]').click();await frame();
  check(getComputedStyle(label).display==='none',flavor+' normal mode has no perk text');
  const missing=socket.querySelector('[data-aegis-compare-generated]');
  check(missing.getAttribute('role')==='img'&&!missing.matches('[role="button"]'),flavor+' missing perk informational');
  check(missing.querySelector('svg').getBoundingClientRect().width===native[0].querySelector('svg').getBoundingClientRect().width,flavor+' missing bubble matches DIM size');
  check(getComputedStyle(native[0].querySelector('circle')).fill==='rgb(33, 104, 68)',flavor+' selected recommendation green');
  check(native[0].hasAttribute('data-aegis-compare-selected')&&!native[1].hasAttribute('data-aegis-compare-selected')&&!missing.hasAttribute('data-aegis-compare-selected'),flavor+' only selected owned perks get rings');
  const outline=node=>getComputedStyle(node.querySelector('svg > circle:last-of-type'));
  check(outline(native[0]).strokeWidth==='6px'&&outline(native[0]).strokeDasharray==='none',flavor+' selected perk has thick solid native outline');
  check([native[1],native[2],missing].every(n=>outline(n).strokeWidth==='3px'&&outline(n).strokeDasharray!=='none'),flavor+' unselected blue, gray, and missing perks have thin dashed outlines');
  let mutations=0;const observer=new MutationObserver(records=>mutations+=records.length);observer.observe(fixture,{subtree:true,attributes:true,childList:true,characterData:true});
  controller.refresh();await frame();observer.disconnect();check(mutations===0,flavor+' unchanged refresh performs no DOM writes');
  order='owned';controller.refresh();await frame();
  check(visual().map(n=>n.dataset.aegisCompareState).join(',')==='selectable,active,missing,other',flavor+' owned-first keeps Aegis order within groups');
  data.activeHashes=[2,12,22,32,42];controller.refresh();await frame();
  check(native[1].dataset.aegisCompareState==='active'&&native[0].dataset.aegisCompareState==='selectable',flavor+' simulated selection refreshes status');
  check(native[1].hasAttribute('data-aegis-compare-selected')&&!native[0].hasAttribute('data-aegis-compare-selected'),flavor+' ring follows simulated selection');
  const replacement=native[1].cloneNode(true);native[1].replaceWith(replacement);controller.refresh();await frame();
  check(replacement.dataset.aegisCompareState==='active',flavor+' native React replacement supported');
  mode='both';controller.refresh();await frame();
  [...fixture.querySelectorAll('.aegis-compare-panel button')].find(n=>n.textContent==='PvP').click();await frame();
  check(socket.querySelectorAll('[data-aegis-compare-state="other"]').length===3,flavor+' PvP recommendations applied');
  check(replacement.hasAttribute('data-aegis-compare-selected')&&replacement.title.includes('compareSelected')&&outline(replacement).strokeWidth==='6px'&&outline(replacement).strokeDasharray==='none',flavor+' selected gray perk retains solid thick outline and accessible label');
  data.sheetWeaponPvP=undefined;controller.refresh();await frame();
  check(!fixture.querySelector('[data-aegis-compare-slot],.aegis-compare-panel'),flavor+' missing sheet restores native grid');
  mode='pve';controller.refresh();await frame();enabled=false;controller.refresh();await frame();
  check(!fixture.querySelector('[data-aegis-compare-state],[data-aegis-compare-selected],[data-aegis-compare-generated],.aegis-compare-panel'),flavor+' disabling cleans up');
  check(native[0].title==='DIM tooltip'&&!native[0].hasAttribute('aria-label'),flavor+' original native attributes restored');
  fixture.innerHTML='<div class="item-popup" data-aegis-item-hash="1" style="width:320px"><div class="overview-native-grid">'+socketHTML+'</div><button id="apply-native">Apply Perks</button></div>';
  const popup=fixture.querySelector('.item-popup');popup.dataset.aegisWeaponPossiblePerks=JSON.stringify(categories);popup.dataset.aegisOverviewActivePerkHashes='1,11,21,31,41';
  const overviewNative=[...popup.querySelectorAll('[role="button"]')];overviewNative.forEach((n,i)=>{n.dataset.aegisOverviewPerkHash=String(Math.floor(i/3)*10+i%3+1);n.addEventListener('click',()=>clicks++);});
  let overviewEnabled=true;
  const overview=initComparePerks({view:'overview',getData:()=>data,getMode:()=> 'pve',getOrder:()=>order,enabled:()=>overviewEnabled});
  overview.refresh();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' Overview has five recommendation columns');
  check(overviewNative[0].hasAttribute('data-aegis-compare-selected')&&!overviewNative[1].hasAttribute('data-aegis-compare-selected'),flavor+' Overview uses native preview selection, independent of inventory grade');
  check(popup.querySelectorAll('[data-aegis-compare-generated]').length===5,flavor+' Overview inserts missing recommendations');
  popup.querySelector('[data-aegis-perk-layout-choice="list"]').click();await frame();
  const overviewName=overviewNative[0].parentElement.querySelector(':scope > .aegis-perk-label');
  check(overviewName.textContent==='Perk 1',flavor+' Overview separate name restored');
  popup.dataset.aegisOverviewActivePerkHashes='2,12,22,32,42';overview.refresh();await frame();
  check(overviewName.textContent==='Perk 2',flavor+' Overview separate name follows selection');
  popup.querySelector('[data-aegis-perk-layout-choice="grid"]').click();await frame();
  const clickCount=clicks;overviewNative[1].click();check(clicks===clickCount+1,flavor+' Overview preserves native click handler');
  popup.dataset.aegisOverviewActivePerkHashes='2,12,22,32,42';overview.refresh();await frame();
  check(overviewNative[1].hasAttribute('data-aegis-compare-selected')&&!overviewNative[0].hasAttribute('data-aegis-compare-selected'),flavor+' Overview selection follows preview updates');
  overviewEnabled=false;overview.refresh();await frame();
  check(!popup.querySelector('[data-aegis-overview-grid],[data-aegis-compare-state],[data-aegis-compare-generated],.aegis-overview-panel'),flavor+' Overview toggle restores native selector');
  check(popup.querySelectorAll('[role="button"]').length===overviewNative.length&&popup.querySelector('#apply-native'),flavor+' Overview keeps native Apply Perks');
  check(!popup.querySelector('.aegis-perk-label,.aegis-perk-name-sizer,[data-aegis-perk-layout]'),flavor+' Overview disabling removes custom labels and layout');
 }
 document.getElementById('fixture').innerHTML='<div style="grid-template-rows:20px"><div role="rowheader">Organizer</div><div role="cell"><div><div class="item"></div></div></div></div><div role="dialog"><div style="grid-template-rows:20px"><div role="rowheader">Other dialog</div></div></div>';
 check(!document.querySelector(COMPARE_BUCKET_SELECTOR),'Unrelated grids are excluded');
 document.getElementById('result').textContent='PASS: '+results.length+' Compare bubble checks';
}
run().catch(e=>document.getElementById('result').textContent='FAIL: '+e.stack);
`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const html = '<!doctype html><title>Compare regression</title><style>'+fs.readFileSync('public/styles.css','utf8')+'.native-socket{display:flex;flex-direction:column}.native-circle{width:32px;height:32px}.native-plug{width:32px;height:32px}</style><pre id="result">Running</pre><div id="fixture"></div><script>'+script+'</script>';
runFixture(html, { reducedMotion: 'reduce' }).catch(error => { console.error(error); process.exitCode = 1; });
