// Self-contained layout and native-selection regression.
const fs = require('node:fs');
const { runFixture } = require('./browser-helpers.cjs');
const ts = require('typescript');
const source = ['activity-mode', 'masterwork', 'compare-selectors', 'compare-bubbles', 'compare-perks'].map(name => fs.readFileSync('src/'+name+'.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'')).join('\n');
const script = ts.transpileModule(`const getRecommendedMasterworks=sheet=>sheet.mw?sheet.mw.split('/'):[], getLocalizedStatName=stat=>stat; const t=key=>key, getLocalizedPerkName=(_hash,name)=>name, getPerkIcon=()=>undefined, getPerkHashFromEnglish=()=>null;\n` + source + `
const results=[];
function check(value,label){if(!value)throw new Error(label);results.push(label);}
const frame=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));
async function run(){
 for(const flavor of ['release','beta','legacy']){
  const fixture=document.getElementById('fixture');
  const bucketClass=flavor==='release'?'opaque_grid':flavor==='beta'?'Compare_bucket_test':'Compare-bucket-test';
  const headerClass=flavor==='release'?'opaque_header':flavor==='beta'?'CompareItem_headerContainer_test':'CompareItem-headerContainer-test';
  const categories={}, perksMap={}, all=[];
  const icon=hash=>'https://www.bungie.net/common/'+hash+'.png';
  const nativeSocket=(slot,i)=>{
   const base=i*10; categories[slotKeys[i]]=[1,2,3].map(n=>'Perk '+(base+n));
   [1,2,3].forEach(n=>perksMap[base+n]={name:'Perk '+(base+n),icon:icon(base+n)});
   [4,2,1].forEach((n,index)=>all.push({type:slot,name:'Perk '+(base+n),hash:base+n,icon:icon(base+n),rankIndex:index+1}));
   return '<div class="native-socket">'+[1,2,3].map(n=>'<div role="button" class="native-plug" title="DIM tooltip"><div><svg viewBox="0 0 100 100" class="native-circle"><circle cx="50" cy="50" r="48"/><image href="'+icon(base+n)+'" width="80" height="80"/><circle cx="50" cy="50" r="46" fill="transparent"/></svg></div></div>').join('')+'</div>';
  };
  const socketHTML=slots.map(nativeSocket).join('');
  fixture.innerHTML='<div role="dialog"><div class="native-toolbar"><a href="/organizer">Show in Organizer</a></div><div class="'+bucketClass+'" style="grid-template-rows:80px auto 40px;grid-template-columns:0px 100px;display:grid;grid-auto-flow:column;grid-auto-columns:220px 1px"><div></div><div class="native-highlight"></div><div class="native-highlight"></div><div></div><div role="rowheader"><div>Perks</div></div><div role="rowheader"><div>Mods</div></div>'+[1,2].map(id=>'<div class="'+headerClass+'"><div><div class="item" data-aegis-item-hash="'+id+'"></div></div></div><div role="cell"><div style="display:flex;gap:4px">'+socketHTML+'</div></div><div role="cell" class="native-mods"><div>Mods</div></div><div style="grid-row:1 / -1"></div>').join('')+'</div></div>';
  fixture.querySelectorAll('.item').forEach(item=>item.dataset.aegisWeaponPossiblePerks=JSON.stringify(categories));
  const bucket=fixture.querySelector(COMPARE_BUCKET_SELECTOR);
  check(!!bucket,flavor+' grid detected');
  const native=[...fixture.querySelectorAll('[role="button"]')];
  let clicks=0; native.forEach(node=>node.addEventListener('click',()=>clicks++));
  const data={equippedMasterwork:'Range',sheetWeapon:{mw:'Range/Handling'},sheetWeaponPvE:{mw:'Range'},sheetWeaponPvP:{mw:'Stability'},perksMap,activeHashes:[1,11,21,31,41],sheetPerks:{all},sheetPerksPvE:{all},sheetPerksPvP:{all:all.filter(p=>p.rankIndex===1)}};
  let enabled=true,order='sheet',mode='pve';
  const enhancements={104:4,105:5};
  let secondData;
  const controller=initComparePerks({getEnhancedToNormal:()=>enhancements,getData:item=>item.dataset.aegisItemHash==='2'&&secondData||data,getMode:()=>mode,getOrder:()=>order,enabled:()=>enabled});
  controller.refresh();await frame();
  check(fixture.querySelectorAll('[data-aegis-masterwork-cell] > .aegis-masterwork-recommendations').length===2&&!fixture.querySelector('.native-mods .aegis-masterwork-recommendations'),flavor+' masterworks have their own line under perks in each Compare column');
  check(fixture.querySelector('.aegis-masterwork-matched').textContent.includes('Range'),flavor+' equipped masterwork highlighted');
  check(!fixture.querySelector('.aegis-masterwork-label'),flavor+' no visible MW label');
  const mods=fixture.querySelector('.native-mods'), modsSize=mods.getBoundingClientRect();
  const mwRow=fixture.querySelector('.aegis-masterwork-recommendations');
  const mwChips=[...mwRow.children];
  check(Math.abs(mwChips[0].getBoundingClientRect().top-mwChips[1].getBoundingClientRect().top)<1&&mwChips[1].getBoundingClientRect().left>=mwChips[0].getBoundingClientRect().right,flavor+' Compare masterworks sit side by side');
  check(mwRow.getBoundingClientRect().top>=mwRow.previousElementSibling.getBoundingClientRect().bottom&&mwRow.parentElement.nextElementSibling===mods,flavor+' masterwork line follows perks before native mods');
  data.sheetWeapon.mw='Range';controller.refresh();await frame();
  const singleMwStyle=getComputedStyle(mwRow.querySelector('.aegis-masterwork-chip'));
  check(singleMwStyle.fontSize==='11px'&&singleMwStyle.padding==='2px 6px',flavor+' single Compare masterwork uses normal tag size');
  check(mods.getBoundingClientRect().width===modsSize.width&&mods.getBoundingClientRect().height===modsSize.height,flavor+' normal masterwork tag preserves mods geometry');
  data.sheetWeapon.mw='Range/Handling';controller.refresh();await frame();
  check([...mwRow.children].every(chip=>getComputedStyle(chip).fontSize==='11px'&&getComputedStyle(chip).padding==='2px 6px'),flavor+' two Compare masterworks use full size');

  check(fixture.querySelectorAll('[data-aegis-compare-slot]').length===10,flavor+' all five slots in both columns');
  check(!fixture.querySelector('[data-aegis-compare-state][title],.aegis-perk-label[title]'),flavor+' recommended perks have no browser title tooltips');
  check(!fixture.querySelector('.aegis-compare-grade,.aegis-compare-table'),flavor+' no duplicate grades or text table');
  check(native.every((node,i)=>node===fixture.querySelectorAll('[role="button"]')[i]),flavor+' native nodes and DOM order preserved');
  native[1].click(); check(clicks===1,flavor+' native click handler preserved');
  const socket=fixture.querySelector('[data-aegis-compare-slot]');
  const visual=()=>[...socket.querySelectorAll('[data-aegis-compare-state]')].sort((a,b)=>Number(getComputedStyle(a).order)-Number(getComputedStyle(b).order));
  check(visual().map(n=>n.dataset.aegisCompareState).join(',')==='missing,selectable,active,other',flavor+' Aegis order and all four colors');
  const positions=visual().map(n=>n.getBoundingClientRect());
  const gaps=positions.slice(1).map((r,i)=>r.top-positions[i].bottom);
  check(gaps.every(gap=>Math.abs(gap-gaps[0])<0.1),flavor+' uniform grid spacing including gray perks');
  check(['none','normal'].includes(getComputedStyle(socket,'::before').content),flavor+' column headers removed');
  fixture.querySelector('[data-aegis-perk-layout-choice="list"]').click();await frame();
  check(fixture.querySelector('a[href="/organizer"]').nextElementSibling.matches('.aegis-perk-layout-toggle'),flavor+' layout button follows Organizer');
  check(!fixture.querySelector('.aegis-perk-layout-toggle').textContent&&fixture.querySelector('.aegis-perk-layout-toggle .fa-th.app-icon'),flavor+' DIM icon replaces text controls');
  const label=socket.querySelector(':scope > .aegis-perk-label');
  check(label.textContent==='Perk 1',flavor+' separate selected name restored');
  check(!socket.querySelector('[data-aegis-compare-state] .aegis-perk-label'),flavor+' bubbles contain no inline names');
  check(visual().every(node=>node.getBoundingClientRect().width===28),flavor+' all list bubbles remain circular');
  check(Math.abs(visual()[0].getBoundingClientRect().left-Math.max(...[...socket.parentElement.querySelectorAll(".aegis-perk-label")].map(node=>node.getBoundingClientRect().right))-4)<.1,flavor+' name-to-bubble gap is four pixels');
  const savedName=data.perksMap[2].name;
  data.perksMap[2].name='A much longer unselected perk name';controller.refresh();await frame();
  const before=socket.parentElement.getBoundingClientRect().width;
  const stablePositions=()=>JSON.stringify(visual().map(node=>[node.getBoundingClientRect().x,node.getBoundingClientRect().y]));
  const beforePositions=stablePositions();
  data.activeHashes=[2,12,22,32,42];controller.refresh();await frame();
  check(label.textContent===data.perksMap[2].name,flavor+' separate name follows long selection');
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' longest selection preserves column width and bubble positions');
  data.activeHashes=[1,11,21,31,41];controller.refresh();await frame();
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' shorter selection retains reserved width');
  data.activeHashes=[];controller.refresh();await frame();
  check(socket.parentElement.getBoundingClientRect().width===before&&stablePositions()===beforePositions,flavor+' empty selection retains reserved width');
  data.perksMap[2].name=savedName;
  data.activeHashes=[1,11,21,31,41];controller.refresh();await frame();
  fixture.querySelector('[data-aegis-perk-layout-choice="grid"]').click();await frame();
  check(getComputedStyle(label).display==='none',flavor+' normal mode has no perk text');
  const missing=socket.querySelector('[data-aegis-compare-generated]');
  check(missing.getAttribute('role')==='img'&&!missing.matches('[role="button"]'),flavor+' missing perk informational');
  check(missing.querySelector('svg').getBoundingClientRect().width===native[0].querySelector('svg').getBoundingClientRect().width,flavor+' missing bubble matches DIM size');
  check(getComputedStyle(native[0].querySelector('circle')).fill==='rgb(33, 104, 68)',flavor+' selected recommendation green');
  check(native[0].hasAttribute('data-aegis-compare-selected')&&!native[1].hasAttribute('data-aegis-compare-selected')&&!missing.hasAttribute('data-aegis-compare-selected'),flavor+' only selected owned perks get rings');
  const outline=node=>getComputedStyle(node.querySelector('svg > circle:last-of-type'));
  check(outline(native[0]).strokeWidth==='6px'&&outline(native[0]).strokeDasharray==='none',flavor+' selected perk has thick solid native outline');
  check([native[1],native[2],missing].every(n=>outline(n).strokeWidth==='3px'&&outline(n).strokeDasharray!=='none'),flavor+' unselected blue, gray, and missing perks have thin dashed outlines');
  let mutations=0;const observer=new MutationObserver(records=>mutations+=records.length);observer.observe(fixture,{subtree:true,attributes:true,childList:true,characterData:true});
  controller.refresh();await frame();observer.disconnect();check(mutations===0,flavor+' unchanged refresh performs no DOM writes');
  const enhancedMarker=document.createElementNS('http://www.w3.org/2000/svg','path');enhancedMarker.setAttribute('fill','#eade8b');native[0].querySelector('svg').append(enhancedMarker);
  all.push({type:'barrel',name:'Perk 5',hash:105,icon:icon(105),rankIndex:5});controller.refresh();await frame();
  check([...socket.querySelectorAll('[data-aegis-compare-generated]')].every(node=>[104,105].includes(Number(node.dataset.aegisComparePerkHash))&&node.querySelector('svg > path')),flavor+' all missing perks in enhanced column use enhanced definitions and markers');
  enhancedMarker.remove();controller.refresh();await frame();
  check([...socket.querySelectorAll('[data-aegis-compare-generated]')].every(node=>[4,5].includes(Number(node.dataset.aegisComparePerkHash))&&!node.querySelector('svg > path')),flavor+' normal column removes mixed enhanced missing definitions');
  all.pop();controller.refresh();await frame();
  check(!fixture.querySelector('[data-aegis-compare-legend]'),flavor+' recommendation legend removed');
  check(!fixture.querySelector('.aegis-compare-panel strong'),flavor+' Compare has no recommendation heading');
  order='owned';controller.refresh();await frame();
  check(visual().map(n=>n.dataset.aegisCompareState).join(',')==='selectable,active,missing,other',flavor+' owned-first keeps Aegis order within groups');
  data.activeHashes=[2,12,22,32,42];controller.refresh();await frame();
  check(native[1].dataset.aegisCompareState==='active'&&native[0].dataset.aegisCompareState==='selectable',flavor+' simulated selection refreshes status');
  check(native[1].hasAttribute('data-aegis-compare-selected')&&!native[0].hasAttribute('data-aegis-compare-selected'),flavor+' ring follows simulated selection');
  const replacement=native[1].cloneNode(true);native[1].replaceWith(replacement);controller.refresh();await frame();
  check(replacement.dataset.aegisCompareState==='active',flavor+' native React replacement supported');
  check(!fixture.querySelector('.aegis-compare-context'),flavor+' context switch absent in PvE-only mode');
  mode='both';controller.refresh();await frame();
  const contextSwitch=fixture.querySelector('.aegis-compare-context');
  check(contextSwitch?.dataset.context==='pve',flavor+' sliding switch starts in PvE');
  check(fixture.querySelectorAll('.aegis-compare-context').length===1&&contextSwitch.closest('[role="rowheader"]').hasAttribute('data-aegis-perks-header'),flavor+' one Compare switch sits below the far-left Perks label');
  const perkHeader=contextSwitch.closest('[role="rowheader"]');
  const headerEvents=[];
  const pressEvents=['click','pointerdown','pointerup','pointercancel','mousedown','mouseup','touchstart','touchend','touchcancel','keydown','keyup'];
  pressEvents.forEach(type=>perkHeader.addEventListener(type,event=>headerEvents.push(event.type)));
  for(const button of contextSwitch.querySelectorAll('button')) {
    for(const type of pressEvents) {
      const event=type.startsWith('key')?new KeyboardEvent(type,{key:'Enter',bubbles:true,cancelable:true}):new Event(type,{bubbles:true,cancelable:true});
      button.dispatchEvent(event);
      check(!event.defaultPrevented,flavor+' switch preserves native activation for '+type);
    }
    await frame();
    check(contextSwitch.dataset.context===button.dataset.aegisContext,flavor+' isolated switch still changes context');
  }
  check(headerEvents.length===0,flavor+' mouse, touch, and keyboard switch events never reach sortable header');
  perkHeader.querySelector(':scope > div').click();
  check(headerEvents.join(',')==='click',flavor+' native Perks label remains sortable');
  [...fixture.querySelectorAll('.aegis-compare-panel button')].find(n=>n.textContent==='PvP').click();await frame();
  check(contextSwitch===fixture.querySelector('.aegis-compare-context')&&contextSwitch.dataset.context==='pvp'&&contextSwitch.querySelector('[data-aegis-context="pvp"]').getAttribute('aria-pressed')==='true',flavor+' switch retains its DOM for sliding animation and updates accessible selection');
  check(fixture.querySelector('.aegis-masterwork-chip').textContent.includes('Stability')&&!fixture.querySelector('.aegis-masterwork-matched'),flavor+' masterworks follow PvP context');
  check(socket.querySelectorAll('[data-aegis-compare-state="other"]').length===3,flavor+' PvP recommendations applied');
  check(replacement.hasAttribute('data-aegis-compare-selected')&&replacement.getAttribute('aria-label').includes('compareSelected')&&outline(replacement).strokeWidth==='6px'&&outline(replacement).strokeDasharray==='none',flavor+' selected gray perk retains solid thick outline and accessible label');
  mode='pvp';controller.refresh();await frame();check(!fixture.querySelector('.aegis-compare-context'),flavor+' context switch absent in PvP-only mode');
  mode='both';controller.refresh();await frame();
  data.sheetWeaponPvP=undefined;controller.refresh();await frame();
  check(!fixture.querySelector('[data-aegis-compare-slot]')&&fixture.querySelector('.aegis-compare-context'),flavor+' missing sheet restores native grid while retaining activity switch');
  fixture.querySelector('[data-aegis-context="pve"]').click();await frame();
  check(fixture.querySelectorAll('[data-aegis-compare-slot]').length===10,flavor+' can return to available PvE recommendations');
  mode='pve';controller.refresh();await frame();enabled=false;controller.refresh();await frame();
  check(!fixture.querySelector('[data-aegis-compare-state],[data-aegis-compare-selected],[data-aegis-compare-generated],.aegis-compare-panel'),flavor+' disabling cleans up');
  check(!fixture.querySelector('.aegis-masterwork-recommendations,[data-aegis-masterwork-cell]'),flavor+' disabling removes masterworks and mods layout');
  check(native[0].title==='DIM tooltip'&&!native[0].hasAttribute('aria-label'),flavor+' original native attributes restored');
  enabled=true;mode='both';data.sheetWeaponPvE=undefined;data.sheetWeaponPvP={mw:'Stability'};
  controller.refresh();await frame();
  check(fixture.querySelector('.aegis-compare-context')&&!fixture.querySelector('[data-aegis-compare-slot]'),flavor+' PvP-only weapon exposes switch on initial PvE context');
  fixture.querySelector('[data-aegis-context="pvp"]').click();await frame();
  check(fixture.querySelectorAll('[data-aegis-compare-slot]').length===10,flavor+' initially unavailable context can reach PvP recommendations');
  const activityData={sheetWeaponPvE:data.sheetWeaponPvE,sheetWeaponPvP:data.sheetWeaponPvP,sheetPerksPvE:data.sheetPerksPvE,sheetPerksPvP:data.sheetPerksPvP};
  data.sheetWeaponPvE=undefined;data.sheetWeaponPvP=undefined;data.sheetPerksPvE=undefined;data.sheetPerksPvP=undefined;
  mode=resolveActivityMode('lightgg','both');controller.refresh();await frame();
  check(fixture.querySelectorAll('[data-aegis-compare-slot]').length===10&&!fixture.querySelector('.aegis-compare-context'),flavor+' Light.gg keeps Compare recommendations with a saved Both preference');
  Object.assign(data,activityData);
  enabled=false;controller.refresh();await frame();data.sheetWeaponPvE={mw:'Range'};
  fixture.innerHTML='<div class="item-popup" data-aegis-item-hash="1" style="display:inline-flex"><div class="gi12X5mX" style="width:320px"><div class="overview-native-grid"><button id="native-layout" title="List style"><span class="fas fa-list app-icon"></span></button>'+socketHTML+'</div><button id="apply-native">Apply Perks</button></div><div style="width:40px">Actions</div></div>';
  const popup=fixture.querySelector('.item-popup');popup.dataset.aegisWeaponPossiblePerks=JSON.stringify(categories);popup.dataset.aegisOverviewActivePerkHashes='1,11,21,31,41';
  const nativeLayout=popup.querySelector('#native-layout');let nativeLayoutClicks=0;nativeLayout.addEventListener('click',()=>{nativeLayoutClicks++;const outer=popup.querySelector('.overview-native-grid'),list=outer.classList.toggle('native-list');if(list){const inner=document.createElement('div');inner.className='overview-native-list';inner.append(...outer.querySelectorAll('.native-socket'));outer.append(inner);}else{const inner=outer.querySelector('.overview-native-list');outer.append(...inner.children);inner.remove();}nativeLayout.firstElementChild.className=list?'fas fa-th app-icon':'fas fa-list app-icon';});
  const geometry=node=>{const c=getComputedStyle(node);return JSON.stringify([c.display,c.flexDirection,c.gap,c.padding,c.borderRightWidth,c.borderBottomWidth,c.alignItems,c.width]);};
  const nativeGeometry=[...popup.querySelectorAll('.native-socket,.native-plug')].map(geometry);
  const overviewNative=[...popup.querySelectorAll('[role="button"]')];overviewNative.forEach((n,i)=>{n.dataset.aegisOverviewPerkHash=String(Math.floor(i/3)*10+i%3+1);n.addEventListener('click',()=>clicks++);});
  let overviewEnabled=true,overviewMode='pve';
  const overview=initComparePerks({view:'overview',getData:()=>data,getMode:()=>overviewMode,getOrder:()=>order,enabled:()=>overviewEnabled});
  overview.refresh();await frame();
  check(getComputedStyle(popup.querySelector('.aegis-overview-panel strong')).textTransform==='uppercase',flavor+' Overview retains uppercase recommendation heading');
  check(popup.querySelector('.overview-native-grid').nextElementSibling.matches('.aegis-overview-footer')&&!!popup.querySelector('.aegis-overview-footer > .aegis-masterwork-recommendations'),flavor+' Overview masterworks directly below perks');
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' Overview has five recommendation columns');
  check(overviewNative[0].hasAttribute('data-aegis-compare-selected')&&!overviewNative[1].hasAttribute('data-aegis-compare-selected'),flavor+' Overview uses native preview selection, independent of inventory grade');
  check(!popup.querySelector('[data-aegis-compare-state][title],.aegis-perk-label[title]'),flavor+' Overview perks have no duplicate browser tooltips');
  check(popup.querySelectorAll('[data-aegis-compare-generated]').length===5,flavor+' Overview inserts missing recommendations');
  check(!popup.querySelector('[data-aegis-perk-layout-choice],.aegis-perk-label,.aegis-perk-name-sizer'),flavor+' Overview keeps native labels and layout controls');
  check(JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug:not([data-aegis-compare-generated])')].map(geometry))===JSON.stringify(nativeGeometry),flavor+' Overview retains native grid spacing and separators');
  check(nativeLayout===popup.querySelector('#native-layout')&&getComputedStyle(nativeLayout).display!=='none',flavor+' original DIM layout button remains visible');
  const popupBody=popup.querySelector('.gi12X5mX');
  const headerAligned=()=>{const h=popup.querySelector('.aegis-overview-panel').getBoundingClientRect(),b=nativeLayout.getBoundingClientRect();return Math.abs(h.top+h.height/2-b.top-b.height/2)<1;};
  check(headerAligned(),flavor+' native grid toggle shares the Overview header line');
  check(popupBody.getBoundingClientRect().width===320&&popupBody.style.width==='320px',flavor+' fitting grid retains native popup width');
  nativeLayout.click();await frame();check(nativeLayoutClicks===1,flavor+' native layout handler retained');
  overview.refresh();await frame();
  const overviewName=overviewNative[0].parentElement.querySelector('.aegis-perk-label');
  check(overviewName?.textContent==='Perk 1'&&getComputedStyle(overviewName).display==='block',flavor+' Overview list uses Compare selected names');
  check(overviewNative.every(node=>node.getBoundingClientRect().width===28),flavor+' Overview list uses Compare bubble sizes');
  check(headerAligned()&&nativeLayout.parentElement===popup.querySelector('.overview-native-grid'),flavor+' list toggle stays on header without moving its React-owned node');
  const shortName=data.perksMap[2].name;
  popup.style.position='fixed';popup.style.left=(innerWidth-popup.getBoundingClientRect().width-12)+'px';
  const nativeLeft=popup.style.left;
  popup.dataset.popperPlacement='bottom';
  const arrow=document.createElement('div');arrow.className='arrow';arrow.style.cssText='position:absolute;left:50px;width:8px';popup.append(arrow);
  const arrowX=arrow.getBoundingClientRect().left;
  data.perksMap[2].name='A much longer recommended weapon perk name';
  const extraPerks=Array.from({length:5},(_,i)=>({type:'barrel',name:'Extra '+i,hash:200+i,rankIndex:10+i}));
  all.push(...extraPerks);overview.refresh();await frame();
  const expandedGrid=popup.querySelector('[data-aegis-perk-layout="list"]');
  check(popupBody.getBoundingClientRect().width>320&&expandedGrid.scrollWidth<=expandedGrid.clientWidth+1,flavor+' long perk names and extra bubbles expand content enough to remove horizontal scrolling');
  check(popup.getBoundingClientRect().width===popupBody.getBoundingClientRect().width+40,flavor+' popup action rail stays beside expanded content');
  check(popup.getBoundingClientRect().right<=innerWidth-11&&popup.getBoundingClientRect().left>=11,flavor+' expanded popup stays inside viewport near right edge');
  check(Math.abs(arrow.getBoundingClientRect().left-arrowX)<1,flavor+' popup arrow retains its anchor after viewport shift');
  popup.style.left='-40px';overview.refresh();await frame();
  check(popup.getBoundingClientRect().left>=11,flavor+' DIM position updates near left edge are clamped');
  const stableLeft=popup.style.left;overview.refresh();await frame();
  check(popup.style.left===stableLeft,flavor+' repeated positioning does not drift');
  popup.style.left=nativeLeft;overview.refresh();await frame();
  all.splice(all.length-extraPerks.length);data.perksMap[2].name=shortName;overview.refresh();await frame();
  check(popupBody.getBoundingClientRect().width===320,flavor+' fitting list returns to native width');
  check(popup.style.left===nativeLeft&&arrow.style.left==='50px',flavor+' shrinking restores DIM position and arrow');
  popup.style.removeProperty('position');popup.style.removeProperty('left');arrow.remove();
  popupBody.style.width='600px';overview.refresh();await frame();
  check(popupBody.getBoundingClientRect().width===600,flavor+' never shrinks a wider DIM popup');
  popupBody.style.width='320px';overview.refresh();await frame();
  const listWidth=overviewNative[0].parentElement.parentElement.getBoundingClientRect().width;
  popup.dataset.aegisOverviewActivePerkHashes='2,12,22,32,42';overview.refresh();await frame();
  check(overviewName.textContent==='Perk 2'&&overviewNative[0].parentElement.parentElement.getBoundingClientRect().width===listWidth,flavor+' Overview list names follow preview without resizing');
  check(popup.querySelector('#apply-native')&&getComputedStyle(nativeLayout).display!=='none',flavor+' Overview list retains Apply Perks and native layout button');
  nativeLayout.click();overview.refresh();await frame();
  check(!popup.querySelector('[data-aegis-perk-layout],.aegis-perk-label,.aegis-perk-name-sizer'),flavor+' returning to grid removes custom list layout');
  check(JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug:not([data-aegis-compare-generated])')].map(geometry))===JSON.stringify(nativeGeometry),flavor+' returning to grid restores native spacing');
  const clickCount=clicks;overviewNative[1].click();check(clicks===clickCount+1,flavor+' Overview preserves native click handler');
  popup.dataset.aegisOverviewActivePerkHashes='2,12,22,32,42';overview.refresh();await frame();
  check(overviewNative[1].hasAttribute('data-aegis-compare-selected')&&!overviewNative[0].hasAttribute('data-aegis-compare-selected'),flavor+' Overview selection follows preview updates');
  check(!popup.querySelector('.aegis-compare-context')&&!popup.querySelector('.aegis-overview-panel').textContent.includes('PvE'),flavor+' Overview hides context control and label in PvE-only mode');
  data.sheetWeaponPvP={mw:'Stability'};overviewMode='both';overview.refresh();await frame();
  const overviewSwitch=popup.querySelector('.aegis-compare-context');
  check(overviewSwitch?.parentElement.matches('.aegis-overview-footer')&&overviewSwitch?.dataset.context==='pve',flavor+' Overview uses the Compare slider in Both mode');
  overviewSwitch.querySelector('[data-aegis-context="pvp"]').click();await frame();
  check(overviewSwitch===popup.querySelector('.aegis-compare-context')&&overviewSwitch.dataset.context==='pvp',flavor+' Overview keeps slider mounted for animation');
  check(popup.querySelector('.aegis-masterwork-chip').textContent.includes('Stability'),flavor+' Overview slider updates recommendation context');
  data.sheetWeaponPvP=undefined;overview.refresh();await frame();
  check(popup.querySelector('.aegis-compare-context')&&!popup.querySelector('[data-aegis-compare-slot]'),flavor+' Overview retains switch when selected activity is missing');
  popup.querySelector('[data-aegis-context="pve"]').click();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' Overview can return to available activity');
  overviewEnabled=false;overview.refresh();await frame();
  data.sheetWeaponPvE=undefined;data.sheetWeaponPvP={mw:'Stability'};overviewEnabled=true;overview.refresh();await frame();
  check(popup.querySelector('.aegis-compare-context')&&!popup.querySelector('[data-aegis-compare-slot]'),flavor+' Overview exposes switch for initially PvP-only weapon');
  popup.querySelector('[data-aegis-context="pvp"]').click();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' Overview reaches initially unavailable PvP recommendations');
  data.sheetWeaponPvE={mw:'Range'};
  overviewMode='pvp';overview.refresh();await frame();
  check(!popup.querySelector('.aegis-compare-context')&&!popup.querySelector('.aegis-overview-panel').textContent.includes('PvP'),flavor+' Overview hides context control and label in PvP-only mode');
  overviewMode='pve';overview.refresh();await frame();
  data.sheetWeapon.mw='';overview.refresh();await frame();check(!popup.querySelector('.aegis-masterwork-recommendations'),flavor+' absent masterwork recommendations remove row');
  // React can replace the sockets before the main-world bridge annotates them.
  // Check the first paint, not just the final settled layout.
  const savedPanel=popup.querySelector('.aegis-overview-panel');
  const layoutObserver=new MutationObserver(records=>overview.observe(records));
  layoutObserver.observe(popup,{childList:true,subtree:true,attributes:true,attributeFilter:['data-aegis-overview-active-perk-hashes','data-aegis-overview-perk-hash']});
  for(const list of [true,false]) {
    const replacement=document.createElement('div');replacement.className='overview-native-grid'+(list?' native-list':'');
    replacement.innerHTML='<button id="native-layout"><span class="fas '+(list?'fa-th':'fa-list')+' app-icon"></span></button>'+(list?'<div class="overview-native-list">'+socketHTML+'</div>':socketHTML);
    popup.querySelector('.overview-native-grid').replaceWith(replacement);
    await new Promise(resolve=>requestAnimationFrame(resolve));
    check(replacement.previousElementSibling===savedPanel&&savedPanel.isConnected,flavor+' Overview keeps header before first paint during '+(list?'list':'grid')+' remount');
    const headerBottom=savedPanel.getBoundingClientRect().bottom,top=replacement.getBoundingClientRect().top;
    replacement.querySelectorAll('[role="button"]').forEach((node,i)=>node.dataset.aegisOverviewPerkHash=String(Math.floor(i/3)*10+i%3+1));
    await frame();
    check(replacement.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' Overview enhances newly annotated sockets with unchanged selection');
    check(savedPanel.getBoundingClientRect().bottom===headerBottom&&replacement.getBoundingClientRect().top===top,flavor+' delayed annotations do not shift Overview header or perk container');
  }
  layoutObserver.disconnect();
  overviewEnabled=false;overview.refresh();await frame();
  check(!popup.querySelector('[data-aegis-overview-grid],[data-aegis-compare-state],[data-aegis-compare-generated],.aegis-overview-panel'),flavor+' Overview toggle restores native selector');
  check(popup.querySelectorAll('[role="button"]').length===overviewNative.length&&popup.querySelector('#apply-native'),flavor+' Overview keeps native Apply Perks');
  check(!popup.querySelector('.aegis-perk-label,.aegis-perk-name-sizer,[data-aegis-perk-layout]'),flavor+' Overview disabling removes custom labels and layout');
  check(!popup.querySelector('[data-aegis-overview-resizable],[data-aegis-overview-controls],[data-aegis-overview-layout-button]')&&!popupBody.style.getPropertyValue('--aegis-overview-required-width')&&popupBody.getBoundingClientRect().width===320,flavor+' disabling restores native width and button placement');
  data.sheetWeaponPvE=undefined;data.sheetWeaponPvP=undefined;data.sheetPerksPvE=undefined;data.sheetPerksPvP=undefined;
  overviewEnabled=true;overviewMode=resolveActivityMode('lightgg','both');overview.refresh();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5&&popup.querySelector('.aegis-overview-panel')&&!popup.querySelector('.aegis-compare-context'),flavor+' Light.gg keeps Overview recommendations with a saved Both preference');
  overviewEnabled=false;overview.refresh();await frame();
  const nativeWithoutRecommendations=JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug')].map(geometry));
  const assertNativeOverview=label=>{
    check(!popup.querySelector('.aegis-overview-panel,.aegis-overview-footer,.aegis-masterwork-recommendations,[data-aegis-compare-state],[data-aegis-perk-layout],[data-aegis-overview-controls],[data-aegis-overview-resizable]')&&!popup.hasAttribute('data-aegis-overview-enhanced'),flavor+' '+label+' has no recommendation formatting');
    check(JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug')].map(geometry))===nativeWithoutRecommendations,flavor+' '+label+' preserves native spacing');
    check(!!popup.querySelector('#native-layout')&&!!popup.querySelector('#apply-native'),flavor+' '+label+' retains DIM controls');
  };
  const ratedSheet=data.sheetWeapon,ratedPerks=data.sheetPerks;
  overviewEnabled=true;
  for(const sheet of [undefined,{source:'Exotic',exoticViability:{}},{source:'Raid'}]){
    data.sheetWeapon=sheet;data.sheetPerks={all:[],matched:[],missing:[]};overview.refresh();await frame();
    assertNativeOverview(sheet?.source||'unrated');
  }
  data.sheetWeapon=ratedSheet;data.sheetPerks=ratedPerks;overview.refresh();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5&&popup.hasAttribute('data-aegis-overview-enhanced'),flavor+' recommendations return on reused Overview');
  let clearedTooltips=0;const onClear=()=>clearedTooltips++;document.addEventListener('aegis-compare-tooltips-hide',onClear);
  data.sheetPerks={all:[],matched:[],missing:[]};overview.refresh();await frame();
  assertNativeOverview('rated to empty transition');
  check(clearedTooltips>0,flavor+' removing recommendations dismisses their tooltips');document.removeEventListener('aegis-compare-tooltips-hide',onClear);
  overviewMode='both';data.sheetWeaponPvE={source:'Exotic'};data.sheetPerksPvE={all:[]};data.sheetWeaponPvP={source:'Exotic'};data.sheetPerksPvP={all:[]};overview.refresh();await frame();
  assertNativeOverview('Both activities empty');
  const nativeList=popup.querySelector('.overview-native-grid'),nativeListInner=document.createElement('div');nativeList.classList.add('native-list');nativeListInner.className='overview-native-list';nativeListInner.append(...nativeList.querySelectorAll('.native-socket'));nativeList.append(nativeListInner);nativeList.querySelector('button span').className='fas fa-th app-icon';
  const emptyListGeometry=JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug')].map(geometry));
  overview.refresh();await frame();
  check(!popup.querySelector('.aegis-overview-panel,[data-aegis-perk-layout],.aegis-perk-label')&&JSON.stringify([...popup.querySelectorAll('.native-socket,.native-plug')].map(geometry))===emptyListGeometry,flavor+' empty recommendations preserve DIM list spacing');
  nativeList.append(...nativeListInner.children);nativeListInner.remove();nativeList.classList.remove('native-list');nativeList.querySelector('button span').className='fas fa-list app-icon';
  data.sheetWeaponPvP={mw:'Stability'};data.sheetPerksPvP=ratedPerks;overview.refresh();await frame();
  check(!!popup.querySelector('.aegis-compare-context')&&!popup.querySelector('[data-aegis-compare-state]'),flavor+' empty PvE keeps native perks and access to recommended PvP');
  popup.querySelector('[data-aegis-context="pvp"]').click();await frame();
  check(popup.querySelectorAll('[data-aegis-compare-slot]').length===5,flavor+' alternate activity recommendations remain reachable');
  overviewMode='pve';data.sheetWeapon={mw:'Range'};data.sheetPerks={all:[]};overview.refresh();await frame();
  check(!!popup.querySelector('.aegis-masterwork-chip')&&!popup.querySelector('[data-aegis-compare-state],[data-aegis-perk-layout]'),flavor+' masterwork-only recommendations preserve native perks');
  overviewEnabled=false;overview.refresh();await frame();
 }
 document.getElementById('fixture').innerHTML='<div style="grid-template-rows:20px"><div role="rowheader">Organizer</div><div role="cell"><div><div class="item"></div></div></div></div><div role="dialog"><div style="grid-template-rows:20px"><div role="rowheader">Other dialog</div></div></div>';
 check(!document.querySelector(COMPARE_BUCKET_SELECTOR),'Unrelated grids are excluded');
 // Use the real layout classes: both declare display with !important.
 const detailsFixture=document.getElementById('fixture');
 for(const compact of [false,true]){
  detailsFixture.innerHTML=['inline','side','armory'].map(kind=>'<div id="'+kind+'" class="aegis-popup-details-card '+(kind==='side'?'aegis-side-panel':kind==='armory'?'aegis-armory-details-card':'')+'"><span class="aegis-details-recommendation-title">Recommendations</span><span class="aegis-details-analysis-title">Analysis</span><div class="aegis-details-body"><div class="aegis-details-perk-recommendations '+(compact?'aegis-perks-matrix-2col':'aegis-details-row aegis-perk-row')+'">Perks</div><div class="aegis-details-row aegis-details-masterwork-recommendations">Masterwork</div><div class="retained">Source, tier, analysis, best in category</div></div></div>').join('');
  for(const [enabled,enhanced] of [[false,false],[true,true],[true,false],[false,false]]){
   detailsFixture.classList.add('item-popup');detailsFixture.toggleAttribute('data-aegis-overview-enhanced',enhanced);
   document.documentElement.toggleAttribute('data-aegis-overview-recommendations',enabled);
   for(const kind of ['inline','side','armory']){
    const card=document.getElementById(kind);
    check((getComputedStyle(card.querySelector('.aegis-details-perk-recommendations')).display!=='none')===(kind==='armory'||!enabled||!enhanced),kind+' perk visibility with compact='+compact+' enabled='+enabled+' enhanced='+enhanced);
    check((getComputedStyle(card.querySelector('.aegis-details-masterwork-recommendations')).display!=='none')===(kind==='armory'||!enabled||!enhanced),kind+' masterwork visibility with compact='+compact+' enabled='+enabled+' enhanced='+enhanced);
    check([...card.querySelectorAll('.retained')].every(node=>getComputedStyle(node).display!=='none'),kind+' retained details with compact='+compact+' enabled='+enabled);
   }
  }
 }
 document.getElementById('result').textContent='PASS: '+results.length+' Compare bubble checks';
}
run().catch(e=>document.getElementById('result').textContent='FAIL: '+e.stack);
`,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
const html = '<!doctype html><title>Compare regression</title><style>'+fs.readFileSync('public/styles.css','utf8')+'.native-mods>div:not(.aegis-masterwork-recommendations){width:40px;height:40px;flex-shrink:0}.native-socket{display:flex;flex-direction:column}.native-circle{width:32px;height:32px}.native-plug{width:32px;height:32px}.overview-native-grid{display:flex;gap:8px;padding:10px;position:relative}.overview-native-grid>button{position:absolute;top:8px;right:10px;width:24px;height:24px}.overview-native-grid>.native-socket{padding:0 5px;border-right:.5px solid #444;gap:4px}.overview-native-grid>.native-socket:last-child{border-right:0}.native-list{display:block}.overview-native-list>.native-socket{flex-direction:row;flex-wrap:wrap;padding:4px 8px;border-right:0;border-bottom:1px solid #333}</style><pre id="result">Running</pre><div id="fixture"></div><script>'+script+'</script>';
runFixture(html, { reducedMotion: 'reduce' }).catch(error => { console.error(error); process.exitCode = 1; });
