const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript');
const moduleSource=ts.transpileModule(fs.readFileSync('src/compare-bubbles.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const exportsObject={};new Function('exports',moduleSource)(exportsObject);
const {planCompareBubbles}=exportsObject;
const owned=[{hash:4,name:'Other',icon:'/4.png',selected:false},{hash:3,name:'Selected',icon:'/3.png',selected:true},{hash:2,name:'Available',icon:'/2.png',selected:false}];
const recs=[{hash:3,name:'Selected',type:'perk1',rankIndex:3},{hash:1,name:'Missing',type:'perk1',rankIndex:1},{hash:2,name:'Available',type:'perk1',rankIndex:2}];
const before=JSON.stringify([owned,recs]);
let plan=planCompareBubbles(recs,owned,'sheet');
assert.deepEqual(plan.map(p=>p.hash),[1,2,3,4]);
assert.deepEqual(plan.map(p=>p.status),['missing','selectable','active','other']);
assert.deepEqual(plan.map(p=>p.selected),[false,false,true,false]);
plan=planCompareBubbles(recs,owned,'owned');
assert.deepEqual(plan.map(p=>p.hash),[2,3,1,4],'Owned recommended perks first, sheet order within groups, gray underneath');
assert.equal(JSON.stringify([owned,recs]),before,'Do not mutate scoring or DIM data');
const localized=planCompareBubbles([{hash:30,name:'Localized',rankIndex:1}], [{hash:30,name:'別名',icon:'/x.png',selected:true}], 'sheet');
assert.equal(localized[0].status,'active','Hash identity works across languages');
assert.equal(planCompareBubbles([...recs,recs[0]],owned,'sheet').length,4,'No duplicate recommendations');
assert.equal(planCompareBubbles([],owned,'sheet').every(p=>p.status==='other'),true);
assert.equal(planCompareBubbles([{hash:9,name:'Enhanced match',icon:'/2.png'}],owned,'sheet')[0].hash,2,'Matching icon handles equivalent plug definitions');
console.log('PASS: Aegis ranking, owned-first ordering, four statuses, selection markers, hash identity, duplicates, and immutable inputs.');
